### DISCUSSION TITLE
Genmon Home Assistant without MQTT

### DISCUSSION THREAD

**Discussion by twistedroutes** [jgyates/genmon#1268] [General]
I was playing around, integrating my [EG4 Inverter into Home Assistant](https://github.com/twistedroutes/eg4_inverter_ha), and I thought it would be great to add Genmon.  I see some MQTT based integrations, but I am not currently using MQTT, so this morning I thought I'd try a quick custom add vs a custom component ( just yet ;-) ).  

I've lately been having very slow responses from the web UI but still fairly rapid responses from the API.  While this is by no means a replacement for the Genmon UI, it does bring together the most common things that I want and need.

In the Dashboard I ahve configured the "Switch to Automatic Mode" to be available if we are in Manual mode, and "Switch to Manual Mode" to be available if we are in Automatic mode.  Start/Stop generator actions are similarly conditional based on the current state.

Here's my dashbaord and the configuration.yaml / scripts.yaml that you can edit.  I'm just using a simple REST sensor to pull the data every 60s (or on action, like start/stop/mode-switch)

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/53ec7eaf-ca84-4ef2-9700-eca34afccaaa" />

configuration.yaml
```yaml
sensor:
  - platform: rest
    name: "Genmon Generator Monitor"
    resource: "http://192.168.12.187:8000/cmd/status_num_json"
    method: GET
    scan_interval: 60
    value_template: "{{ 'OK' if value_json.Status else 'Unknown' }}"
    json_attributes:
      - Status

template:
  - sensor:
      - name: "Genmon Switch State"
        state: >
          {% set switchstate = state_attr('sensor.genmon_generator_monitor', 'Status')[0]['Switch State'] %}
          {{ switchstate if switchstate is defined else 'Unknown' }}

      - name: "Genmon Engine State"
        state: >
          {% set enginestate = state_attr('sensor.genmon_generator_monitor', 'Status')[1]['Engine State'] %}
          {{ enginestate if enginestate is defined else 'Unknown' }}

      - name: "Genmon Battery Voltage"
        state: >
          {% set battvolts = state_attr('sensor.genmon_generator_monitor', 'Status')[2]['Battery']['value'] %}
          {{ battvolts if battvolts is defined else 0.0 }}
        unit_of_measurement: "V"
        device_class: voltage

      - name: "Genmon Engine Speed"
        state: >
          {% set engine = state_attr('sensor.genmon_generator_monitor', 'Status')[3]['Engine'] %}
          {{ engine[7]['Engine Speed'].value | int(default=0) if engine and engine[7] and 'Engine Speed' in engine[7] else 0 }}
        unit_of_measurement: "rpm"

      - name: "Genmon L1-L2 Voltage"
        state: >
          {% set engine = state_attr('sensor.genmon_generator_monitor', 'Status')[3]['Engine'] %}
          {{ engine[2]['Generator L1-L2 Volts'].value | float(default=0) if engine and engine[2] and 'Generator L1-L2 Volts' in engine[2] else 0 }}
        unit_of_measurement: "V"
        device_class: voltage

      - name: "Genmon Load Total (kW)"
        state: >
          {% set engine = state_attr('sensor.genmon_generator_monitor', 'Status')[3]['Engine'] %}
          {{ engine[0]['Load Total (kW)'].value | float(default=0) if engine and engine[0] and 'Load Total (kW)' in engine[0] else 0 }}
        unit_of_measurement: "kW"
        device_class: power
        state_class: measurement

rest_command:
  genmon_set_auto:
    url: "http://192.168.12.187:8000/cmd/setremote?setremote=auto"
    method: GET

  genmon_set_manual:
    url: "http://192.168.12.187:8000/cmd/setremote?setremote=off"
    method: GET

  genmon_start_generator:
    url: "http://192.168.12.187:8000/cmd/setremote?setremote=start"
    method: GET

  genmon_stop_generator:
    url: "http://192.168.12.187:8000/cmd/setremote?setremote=stop"
    method: GET
```

script.yaml
```yaml
genmon_set_auto_mode:
  alias: "Set Generator to Auto Mode"
  sequence:
    - service: rest_command.genmon_set_auto
    - delay: "00:00:02"  # 5 second delay
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.genmon_generator_monitor

genmon_set_manual_mode:
  alias: "Set Generator to Manual Mode"
  sequence:
    - service: rest_command.genmon_set_manual
    - delay: "00:00:02"  # 5 second delay
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.genmon_generator_monitor

genmon_start:
  alias: "Start Generator"
  sequence:
    - service: rest_command.genmon_start_generator
    - delay: "00:00:02"  # 5 second delay
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.genmon_generator_monitor

genmon_stop:
  alias: "Stop Generator"
  sequence:
    - service: rest_command.genmon_stop_generator
    - delay: "00:00:02"  # 5 second delay
    - service: homeassistant.update_entity
      target:
        entity_id: sensor.genmon_generator_monitor

genmon_toggle_mode:
  alias: "Toggle Generator Mode"
  sequence:
    - choose:
        - conditions:
            - condition: state
              entity_id: sensor.genmon_switch_state
              state: "Automatic"
          sequence:
            - service: script.genmon_set_manual_mode
      default:
        - service: script.genmon_set_auto_mode

genmon_toggle_engine:
  alias: "Toggle Generator Engine"
  sequence:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ 'running' in states('sensor.genmon_engine_state')|lower }}"
          sequence:
            - service: script.genmon_stop
      default:
        - service: script.genmon_start
```
